### ISSUE TITLE
Whatever password I type in login, still allows me to enter the system

### ISSUE THREAD

**Issue by MostDeadDeveloper** [martrohelsanchez/Chitty#4]
Replicate: 

- use the username "John" 
- type whatever password in the password section

Whatever password I put, it still allows me to enter the system or interact with the chatting interface.

**Comment by martrohelsanchez** [comment]
Yes, the password authentication wasn’t working as its node.js environment is on “development”. Thank you for pointing that out. I just recently toggled it to the correct environment which is “production”. Now, the backend compares the hashed password on the database to what the user provided and checks if the anti-csrf token on the request header matched its duplicate on the JWT token to prevent CSRFs.

**Comment by MostDeadDeveloper** [comment]
closing said issue since it is a known issue or not a bug
